---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kueue-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
spec:
  # IMPORTANT: No targetNamespaces. This enables "AllNamespaces" mode.
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
spec:
  channel: stable-v1.2
  installPlanApproval: Automatic
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: kueue.openshift.io/v1
kind: Kueue
metadata:
  name: cluster # IMPORTANT: Must be named 'cluster'
spec:
  managementState: Managed
  config:
    integrations:
      frameworks:
      - BatchJob
      - MPIJob
      - RayJob
      - PyTorchJob
      - Pod